//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int RecordID { get; set; }
        public string CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public string ProductName { get; set; }
        public virtual Producto Product { get; set; }
    }
}
