//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        public int ProductID { get; set; }
        [DisplayName("Imagen")]
        public string ProductImg { get; set; }
        [DisplayName("Nombre")]
        public string ProductName { get; set; }
        [DisplayName("Descripción")]
        [StringLength(200)]
        public string ProductDescription { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Por favor, ingrese una serie de números")]
        public Nullable<int> Stock { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Por favor, ingrese una serie de números")]
        public Nullable<int> Precio { get; set; }
        public string Category { get; set; }
    }
}
